networks:
  nginx-webdav-net:
    name: nginx-webdav-net
    driver: bridge

services: 
  nginx-webdav:
    container_name: nginx-webdav
    build: .
    networks:
      - nginx-webdav-net
    volumes:
      - ${PATH_DATA}:/var/www/dav
    ports:
      - 443:443
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBDAV_USERNAME=${USERNAME}
      - WEBDAV_PASSWORD=${PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-fk", "https://localhost/health"]
      start_period: 1m
      interval: 5s
      retries: 10